default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "password"
  host: localhost

development:
  <<: *default
  database: computer_management_development

test:
  <<: *default
  database: computer_management_test

production:
  <<: *default
  database: computer_management_production
